### ISSUE TITLE
RMM 成熟度 - 第三級 REST 的效果疑問 - Rex

### ISSUE THREAD

**Issue by HuaYuan-Tseng** [fresh-tech-lab/fenix-study-group#5]
> 如果做到了第 3 级 REST，那服务端的 API 和客户端也是完全解耦的，你要调整服务数量， 或者同一个服务做 API 升级将会变得非常简单

我的疑問是 為什麼？有哪裡解耦？調整服務數量或做 API 升級有變簡單嗎？
我是真的看不太出來，希望有好心的大大可以幫忙解釋 QQ

**Comment by HuaYuan-Tseng** [comment]
話說，我自己標不了 Label - Question，再麻煩幫忙標一下了，乾蝦～

**Comment by kehao-chen** [comment]
個人的理解實踐是 HATEOAS，RESTful API 風格是依據「資源」來設計，而 HATEOAS 可以讓用戶端從某個資源，知道還有哪些其他相關的資源存在，以及如何對它們進行操作。

可以參考 Martin Fowler 對 REST 成熟度模型的詮釋 [Richardson Maturity Model](https://martinfowler.com/articles/richardsonMaturityModel.html#level3)：

> One obvious benefit of hypermedia controls is that it allows the server to change its URI scheme without breaking clients. As long as clients look up the "addTest" link URI then the server team can juggle all URIs other than the initial entry points.

 HATEOAS 可在不影響用戶端運行下進行 URI 的更改，用戶端需參考對應資源所提供的 URI。

> A further benefit is that it helps client developers explore the protocol. The links give client developers a hint as to what may be possible next.

用戶端也可以探索其他相關資源的使用。

**Comment by emily40830** [comment]
> 話說，我自己標不了 Label - Question，再麻煩幫忙標一下了，乾蝦～

標好嘍
